### ISSUE TITLE
CPUFriend

### ISSUE THREAD

**Issue by nijhawank** [simprecicchiani/Thinkpad-T460s-macOS-OpenCore#1]
I see that you have removed both CPUFriend.kext and CPUFriendDataProvider.kext. My understanding is that you either use the CPUFriendDataProvider.kext or the SSDT-CPU.aml as generated by CPUFriendFriend but you always need CPUFriend.kext.

Are you suggesting that OpenCore does natively what CPUFriend.kext does and therefore not needed?

**Comment by simprecicchiani** [comment]
Yes, you’re right, CPUfriend kext is needed.

**Comment by simprecicchiani** [comment]
This confirms that OpenCore handles perfectly power management, cause I don't really noticed differences between using CPUFriend.kext w/ CPUDataProvider.kext and not using any.
