### ISSUE TITLE
Support for E14

### ISSUE THREAD

**Issue by Abbos92** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#101]
Is this config support for ThinkPad E14?

ProcessorIntel Core i5-10210U 4 x 1.6 - 4.2 GHz, Comet Lake-U
Graphics adapterIntel UHD Graphics 620
Memory16384 MB  
, DDR4-2400, 1 SO-DIMM slot
Display14.00 inch 16:9, 1920 x 1080 pixel 157 PPI, NV140FHM-N48, IPS LED, glossy: no
MainboardIntel Comet Lake-U PCH-LP Premium
StorageSK hynix BC501 HFM512GDHTNG-8310A, 512 GB  
, M.2 2280 PCIe NVMe, 437 GB free

**Comment by simprecicchiani** [comment]
No, I’m sorry, not at all.
