### ISSUE TITLE
Moving windows around freezes on 0.6.7

### ISSUE THREAD

**Issue by marcfusch** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#102]
I,
Just updated to 0.6.7 since i received my new broadcom wifi card. After copying the existing platforminfo and rebooting into 0.6.7, i just noticied that moving arround causes it to freeze until you release the click on the trackpad. This occurs half the time so i had to roll back to 0.6.6. I thought it maybe was an issue with my, just installed, wifi card but it needs no kexts and after rolling back, i had no problem with it installed.

**Comment by simprecicchiani** [comment]
It's not a bug, it's a feature of VoodooRMI which implement force touch but doesn't work properly.
I forgot to disable it in the last release. I'll update it in few minutes.
