### ISSUE TITLE
Hiberination 25 cmos solution (work for my t460s)

### ISSUE THREAD

**Issue by mhl221135** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#103]
Sup guys! I got working hibernation on my T490 with Whiskey Lake cpu using OpenCore bootloader. As I saw "RTC Lock" chipset option isn't the main cause of checksum error, due to I also had this behaviour on my board with disabled RTC Lock in PCH settings. Higher bank (128-255) used by Lenovo for sensitive or diagnostic information like setup settings checksum, that's why checksum error thrown, if any data had been written into it.
So first of all you should use RTCMemoryFixup and HibernationFixup.
Then remove ranges from rtc-blacklist, if you use any, and add 80-AB range into exclude for RTCMemoryFixup (rtcfx_exclude=80-AB). This actions should fix checksum error. After this you need to set HibernateMode to NVRAM.
The main problem - black screen after wake could be fixed by enabling CSM support inside BIOS Setup Utilty, seems it affects memory map and do something tricky which resolves restore from hibernation file into black screen.
Also you can check my set of quirks
[config.plist](https://ghostbin.co/paste/q4h4a)

_Originally posted by @savvamitrofanov in https://github.com/tylernguyen/x1c6-hackintosh/issues/44#issuecomment-696689768_

**Comment by mhl221135** [comment]
Also i have no issues with touchpad after sleep and intel wifi also working fine

**Comment by tom-ek-repo** [comment]
Works for me @X390

**Comment by vihor3** [comment]
Thank you very much. The source you quoted is my model. I have encountered this problem and am seeking a solution
