### ISSUE TITLE
OpenCore old version problem

### ISSUE THREAD

**Issue by iTer99** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#107]
i dont know, but for some reasion OpenCore Configurator say "You seem to have an old version of OpenCore bootloader. This app creates a configuration file for 0.6.8 or higher versions". and i found command in Terminal for check current OpenCore version `nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version`. 
4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version	REL-066-2021-02-02

**Comment by duszmox** [comment]
It seems, i forgot to copy the NVRAM version over to the 0.6.8 config. I will fix it in the next release soon.

**Comment by iTer99** [comment]
> Có vẻ như, tôi đã quên sao chép phiên bản NVRAM sang cấu hình 0.6.8. Tôi sẽ sửa chữa nó trong bản phát hành tiếp theo.

ok thank you so much
