### ISSUE TITLE
MOD BIOS

### ISSUE THREAD

**Issue by iTer99** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#109]
sorry, but what if i mod bios? anyting change?

**Comment by duszmox** [comment]
The bios mod is only needed if you want to use a wifi card, which is blacklisted by Lenovo, and refuses to work. You can read more about [here](https://notthebe.ee/Removing-the-Wi-Fi-Whiteslit-on-Haswell-Thinkpads-T440p-W540-T540-etc.html).
