### ISSUE TITLE
How to dualboot Opencore with Windows

### ISSUE THREAD

**Issue by iTer99** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#112]
I was check this, Bootcamp in Windows work but in MacOS doesn't show up
https://dortania.github.io/OpenCore-Post-Install/multiboot/bootcamp.html
![image](https://user-images.githubusercontent.com/23251203/119263201-477bfb80-bc08-11eb-9a33-835b79f58645.png)

**Comment by duszmox** [comment]
You can set, the default boot OS in the OpenCore bootloader with CTRL+Enter. [Here is some more info](https://www.reddit.com/r/hackintosh/comments/ep0qag/opencore_054_now_supports_default_boot_option/?utm_source=share&utm_medium=ios_app&utm_name=iossmf)

**Comment by iTer99** [comment]
<img width="832" alt="image" src="https://user-images.githubusercontent.com/23251203/124554841-99977a00-de60-11eb-89f8-ff4fb9498a94.png">


1) Use mini Windows via USB Boot have CMD:
diskpart
list disk
select disk 0 (0 is Hard Disk use have Hackintosh)
create part primary size=450
format quick fs=ntfs label=Recovery (creat partition Recovery for Windows)
assign letter=R
set id=“de94bba4-06d1-4d40-a16a-bfd50179d6ac”
gpt attributes=0x8000000000000001
create part msr size=16 (partition MSR, I don't know what is it, but it need for Windows partition)
create part primary (partition for install Windows)
format quick fs=ntfs label=Windows
assign letter=M
2) Mount any ISO Windows then open Setup.exe and install Windows normal
