### ISSUE TITLE
Apple progress bar after login password

### ISSUE THREAD

**Issue by iTer99** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#116]
When i turn on device, my device request password and then show apple progress bar. How can i change it, i want when i turn on device it run apple progress bar first and then login password? thank you so much

**Comment by mhl221135** [comment]
You using hibernate mode ?

**Comment by iTer99** [comment]
> You using hibernate mode ?

i don't know, i shutdown and turn on

**Comment by mhl221135** [comment]
> > You using hibernate mode ?
> 
> i don't know, i shutdown and turn on
Strange, maybe its becouse of slow ssd, dont know

**Comment by iTer99** [comment]
> > > You using hibernate mode ?
> > 
> > 
> > i don't know, i shutdown and turn on
> > Strange, maybe its becouse of slow ssd, dont know

you can see in this video, when him turn on laptop the apple logo will show with progess bar and then password request login, but on my laptop, i turn it on the password request first and then apple logo show with progress bar
https://www.youtube.com/watch?v=SnuQjuIrfc0

**Comment by duszmox** [comment]
You are using FireVault disk encryption, if you turn it off, it will act normally

**Comment by iTer99** [comment]
> You are using FireVault disk encryption, if you turn it off, it will act normally

exactly, thank you so much
