### ISSUE TITLE
Hibrenation Freeze on AC

### ISSUE THREAD

**Issue by marcfusch** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#123]
Hi,
Since forever, my macos installation freezes when it goes into "hibernation" whether it's on mode 3 (i get a black screen) or mode 25, (I get a freeze at the login screen). But that only happends while connected to AC.
On battery there is no problem but if i put my laptop into hibernataion while on battery, and then plug the ac, the same problem occurs.
I have read no such problems online.

**Comment by marcfusch** [comment]
Good news. Btw i'm using bios 1.51, macos 11.5.2 and efi 0.7.2

**Comment by marcfusch** [comment]
Hi, What are you guys bios settings for the reserved igpu memory. I seem to have it in 512mb and I just changed it to 256. Laptop did not crash during the night I tried plugged in into AC.

**Comment by duszmox** [comment]
To my understanding, there is no settings for that in the bios, but if you set the "framebuffer-fbmem" setting to the correct hex under DeviceProperties you can modify the igpu reserved memory. I use the amount specified in the repository.

**Comment by marcfusch** [comment]
![PXL_20210819_100301304](https://user-images.githubusercontent.com/53045672/130050553-2dd7dab2-0705-4673-9b16-697cc87d3e18.jpg)
Hi, There is indeed such an option. And it clearly affects system stability under hibernation. You should include that in the recommended bios settings and try on your own. (yes i'm running the nvmefix, but before i upgraded to my nvme, having a sata drive I encountered the same problem.)
