### ISSUE TITLE
Batteries can't be recognized under windows booting by open core

### ISSUE THREAD

**Issue by hexart** [simprecicchiani/Thinkpad-T460s-macOS-OpenCore#13]
![bat](https://user-images.githubusercontent.com/5528016/83941269-b22bff80-a81c-11ea-851d-f7809cd35a43.png)
![unknowdevices](https://user-images.githubusercontent.com/5528016/83941272-b5bf8680-a81c-11ea-8863-56c6938da405.png)

**Comment by simprecicchiani** [comment]
That was predictable, I didn’t bother with  Windows-sensible patches since using it wasn’t in my plans.  
If you want to implement solutions for it feel to fork the repo and pull request 👍🏻

**Comment by simprecicchiani** [comment]
Moreover, current SSDT and renames patches are from @MSzturc T460 repo, which I think are based on @junaedahmed's T460 repo.

**Comment by hexart** [comment]
https://github.com/daliansky/OC-little/blob/master/08-电池补丁/08-1-Thinkpad/各机型电池补丁/SSDT-NTFY.md

This might be the solution of two physical batteries machine type, FYI.

**Comment by junaedahmed** [comment]
@hexart 
use this one [SSDT-BATC](https://github.com/acidanthera/VirtualSMC/blob/master/Docs/SSDT-BATC.dsl) for dual battery in windows.
