### ISSUE TITLE
Low Trackpad sensitivity

### ISSUE THREAD

**Issue by aidbal** [simprecicchiani/Thinkpad-T460s-macOS-OpenCore#15]
Hey,

I have noticed that trackpad sensitivity is kind of low. What I mean is that sometimes it registers three finger swipe, sometimes it does not. I have to kind of press more firmly compared to a real mac.

I am not talking about "Tracking speed" which just makes your mouse move faster.

Is there anyway I could tweak this? I tried scavenging through various forums, but people only talk there about "Tracking speed" not the actual sensitivty of registering your fingers.

**Comment by simprecicchiani** [comment]
Yeah three finger swipe works only 50% of the times if you are not used to the kind of sensibility it has.
You should look into VoodooPS2 repo to get familiar with how it works, I have never tried to change anything.

**Comment by aidbal** [comment]
Alright, so after fiddling a bit, I have found this package: https://github.com/acidanthera/VoodooPS2. Using it now for a day, it seems like it made the trackpad more responsive (especially the 3 fingers swipe).

Closing it now :)

**Comment by simprecicchiani** [comment]
What do you mean by this package? Acidanthera’s VoodooPS2 kext is already built into my repo’s EFI.
You updated it?

**Comment by aidbal** [comment]
Oh, okay, I thought you were using Rehab's (https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller). 

To answer your question, yeah, I downloaded the latest version (2.1.5)

**Comment by simprecicchiani** [comment]
Newer version are known to cause some issues and lag when performing some actions as discussed in #10 (second part). At least for me it makes all choppy when dragging windows around using physical keys and Trackpoint. But yeah, swipes gestures are smoother in the latest version. Didn’t you noticed some weird behaviours with it?

**Comment by simprecicchiani** [comment]
In addition 2.1.5 will break PrtScr key map if you have one, unless you don’t modify the kext itself.

**Comment by simprecicchiani** [comment]
Hey, I've just updated the repo with a new trackpad kext, It's a lot snappier than before and supports all gestures!
