### ISSUE TITLE
Bluetooth turns on but keeps loading

### ISSUE THREAD

**Issue by thomas-catt** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#152]
### EDIT: FIXED: Lilu was being loaded AFTER BluetoothFixup
I'm probably the dumbest man on earth for not noticing this, but even while knowing well enough that Lilu should load before it's plugins, I still missed this one. You need to load BluetoothFixup **before** Lilu.kext (which is pretty obvious but that's the solution). I got around this while tidying up my plist, using the `ocvalidator` program in OpenCore.

### End of EDIT

**macOS Monetery, T460 with Intel Bluetooth & Wi-Fi card.** When I turn on bluetooth, a loader appears and keeps spinning in the control center.

![image](https://user-images.githubusercontent.com/75628498/169656454-b51929ba-e3f3-453d-abd0-113601bca079.png)

If I open bluetooth preferences, the window shows that bluetooth is turned off, and the *Turn Bluetooth On* button doesn't work at all.

![image](https://user-images.githubusercontent.com/75628498/169656480-119d38d3-bfd8-4f2a-80a4-7bad2282d48f.png)

Bluetooth is completely non-functional. I have an Intel Bluetooth & Wi-Fi card, and am using the Intel WLAN fixes (Wi-Fi works fine) as well. But I noticed that somewhere in *System Information*, my Bluetooth card is being listed as a ***Broadcom*** one (showing "BCM"). Could this be related?

![image](https://user-images.githubusercontent.com/75628498/169656621-363961a9-4f77-4f65-8747-95d616ffc388.png)

 I tried to get rid of Broadcom by editing my plist, but this won't go anywhere. There are more Broadcom traces if I search with the *IORegistryExplorer* app: 

![image](https://user-images.githubusercontent.com/75628498/169656756-b2f3adff-5635-4dd0-b197-f18cf2249760.png)

Any help will be appreciated. Btw thanks for the EFI, mostly this EFI has minimal bugs, I was successful in fixing a few of them, but unfortunately can't find a fix for this.

**Comment by thanosz** [comment]
same here!

**Comment by marcfusch** [comment]
Apple rewrote the bluetooth stack in monterey, breaking compatibility with many devices (mainly old audio codecs).
I went back to Big Sur flawlessly with time machine and bluetooth finally worked again.

**Comment by victorovento** [comment]
I have the same problem

**Comment by thomas-catt** [comment]
I found someone on reddit who had fixed this problem on their machine willing to help. I'll try to apply thise fixes and update

**Comment by thomas-catt** [comment]
accidentally closed the issue sorry

**Comment by thanosz** [comment]
> I found someone on reddit who had fixed this problem on their machine willing to help. I'll try to apply thise fixes and update you guys

Thank you!

**Comment by cyberfunk** [comment]
If you have issues going forward I highly recommend the Broadcom BCM94360CS2 Wi-Fi and Bluetooth Card and the required adapter. I have a Lenovo Yoga 260 and this baby works as well or better than a native MacBook Wifi+BlueTooth setup. Location services Find My Mac etc. I tried Monterey and it worked flawlessly there as well but have returned to Big Sur due to issues with making bootable clones in Monterey.

**Comment by victorovento** [comment]
this worked for me 
https://youtu.be/b4ettyKkcFg

**Comment by thomas-catt** [comment]
Fixed the issue, see the edit for solution.

Closing.

**Comment by HenriqueDelben** [comment]
@thomas-catt I read your edit but i think you mistyped. The fix is to load lilu before or after BluetoolFixup?

**Comment by thomas-catt** [comment]
> [@thomas-catt](https://github.com/thomas-catt) I read your edit but i think you mistyped. The fix is to load lilu before or after BluetoolFixup?

I haven’t dealt with this issue in a long time now but if I remember correctly you’re right I made a typo. Lilu must load before any of its plug-ins. 

I think if you’re on ProperTree, a clean snapshot (Ctrl/Cmd + Shift + R) fixes the kext loading order. If not, give ocvalidate a try.
