### ISSUE TITLE
Big Sur

### ISSUE THREAD

**Issue by diepnt90** [simprecicchiani/Thinkpad-T460s-macOS-OpenCore#16]
Could you install big sur on t460s ?

**Comment by duszmox** [comment]
I've managed to upgrade to Big Sur. It was a journey. I think I will create a pull request with the EFI folder, in case someone else don't want to waste 8 hours messing around with every little detail.

**Comment by simprecicchiani** [comment]
Sure, thanks!

**Comment by simprecicchiani** [comment]
#18
