### ISSUE TITLE
Request for EFI Config for macOS Sequoia

### ISSUE THREAD

**Issue by mortuzahossain** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#190]
Hi, I'm looking for an EFI configuration compatible with macOS Sequoia.

- CPU: Core i5-6200U
- Graphics: Integrated Intel HD Graphics 520
- Memory: 4GB Soldered + 8GB DIMM 2133MHz DDR4, dual-channel
- Display: 14" Full HD (1920x1080) IPS

Would anyone be able to share or guide me to a working EFI for this setup? Thank you!

**Comment by marcfusch** [comment]
Project hasen't been updated in 2 years. I think it is dead unfortunately :/

**Comment by mortuzahossain** [comment]
May be it(**macOS Sequoia**) is not supported.
