### ISSUE TITLE
Windows detect thinkpad as macbookpro

### ISSUE THREAD

**Issue by oNuRix** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#20]
![5745967A-E796-4151-ABF2-E6FA40EF4253](https://user-images.githubusercontent.com/40405226/87940442-e17b9080-ca99-11ea-95a1-8e54f54f68a4.jpeg)
Thanks for your work.

Can’t use Lenovo vantage app or update bios because this problem.

**Comment by hexart** [comment]
That's totally normal, you can press F12 and choose windows when you need to update bios.
