### ISSUE TITLE
T460 1920 x 1080 version?

### ISSUE THREAD

**Issue by aptonline** [simprecicchiani/Thinkpad-T460s-macOS-OpenCore#22]
I've just purchased a non S version of the T460 and looking to install OpenCore and wondering if you know what needs to change in order from your EFI to work on the T460?

Do you think the MacBook13,1 profile would work the same? I'd obviously need to play with the RDM utility for the screen too.

**Comment by simprecicchiani** [comment]
Hi, the configuration should be fully compatible with the T460, but the USB map is different. I would suggest to use this EFI for T460: https://github.com/MSzturc/Lenovo-T460-OpenCore
