### ISSUE TITLE
kernel panic... ㅠㅠ

### ISSUE THREAD

**Issue by sanghyukYoon** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#25]
I installed this boot loader to my T460s (cpu 6200u) But It had a kernel panic like the picture below...
How can i solve this problem?

![KakaoTalk_Photo_2020-09-08-15-52-01](https://user-images.githubusercontent.com/16624147/92442694-48403f00-f1eb-11ea-82cc-fc795a1ab875.jpeg)

**Comment by simprecicchiani** [comment]
Could you be more specific? What are you trying to do?

**Comment by sanghyukYoon** [comment]
SOLVED

https://www.tonymacx86.com/threads/solved-how-to-rebuild-kextcache.224241/
