### ISSUE TITLE
Bluetooth and WLAN Adopter does not work...

### ISSUE THREAD

**Issue by sanghyukYoon** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#26]
I was using Bluetooth and wlan adapter well in the clover environment(RtWlanU1827, AirportBrcmFixup) but after switching to this open core, I used the existing kext but they didn't work at all.
Also, I don't know why batteries don't change at 1%.
Thank you

<img width="692" alt="스크린샷 2020-09-08 오후 10 21 31" src="https://user-images.githubusercontent.com/16624147/92481680-a9830500-f221-11ea-977d-b094244e525c.png">
<img width="307" alt="스크린샷 2020-09-08 오후 10 21 50" src="https://user-images.githubusercontent.com/16624147/92481708-b1db4000-f221-11ea-88e6-bfb32ea8cfcb.png">
<img width="1392" alt="스크린샷 2020-09-08 오후 10 23 18" src="https://user-images.githubusercontent.com/16624147/92481881-ed760a00-f221-11ea-8516-d6baf83143e6.png">

**Comment by simprecicchiani** [comment]
Did you performed a full wipe of clover stuff? Delete all third party kexts and rebuild cache?

**Comment by simprecicchiani** [comment]
Also, I don't know which GUI software you're using to open the configuration but it looks like you have some Voodoo kexts enabled when they shouldn't.

**Comment by duszmox** [comment]
It's called OpenCore configurator, and it's a ton of bullcrap. It messes with your config.plist if you don't have the correct version which matches with your OC version, and I also read that even if you have the correct one it could cause serious damage to the config file. You should really use propertree or some other plist editor.

**Comment by duszmox** [comment]
Also if the battery status doesn't work, you should replace the SMCBatteryManager with the RehabMan's ACPIBatteryManager.

**Comment by sanghyukYoon** [comment]
Yes I wiped all
