### ISSUE TITLE
Sreen Flicker on lower brightness

### ISSUE THREAD

**Issue by SamuelG13** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#28]
Hi. I successfully instaled macOS Catalina on my ThinkPad, everything works great except the screen. When the brightness is at maximum there is no flicker but at lower brightness, the flicker appears and I can't use the laptop it just hurts my eyes. Thank you in advance !

**Comment by simprecicchiani** [comment]
Can you post your specs?

**Comment by SamuelG13** [comment]
Non-touchscreen 1920x1080p 60hz screen, core i5-6200u, 16gb ram, sandisk ssd

**Comment by simprecicchiani** [comment]
Sorry, can't help you with that. Try to ask on r/Hackintosh or somewhere else.

**Comment by simprecicchiani** [comment]
Please try [this release](https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore/releases/tag/0.6.2.1).

**Comment by simprecicchiani** [comment]
I assume it has been fixed like #30 .
