### ISSUE TITLE
Wifi for Intel chip

### ISSUE THREAD

**Issue by alexdelli** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#29]
Hi, sorry this is not an issue, but a request of implement a guide for intel wifi. Now with AirportItlwm.kext is it not necessary to use Heliport. Maps, Handoff , Airport are working (Big Sur and Catalina).  It's very simple, just put AirportItlwm.kext in EFI and ADD Kernel in config.
What do you think about it?

**Comment by simprecicchiani** [comment]
I didn't see that coming! It seems great news, I'll check it out as soon as I have some free time.

**Comment by alexdelli** [comment]
> Edit: I'm thinking of buying a T490 



Noooooooooooo, we need you againnnn :((

**Comment by simprecicchiani** [comment]
Kexts are in (disabled by default, make sure to enable them).
Waiting for your feedback.

**Comment by alexdelli** [comment]
For me it's ok! Fantastic

**Comment by sanghyukYoon** [comment]
I did it and it works well

**Comment by sanghyukYoon** [comment]
Here is the link https://github.com/1hbb/OpenIntelWireless-Factory

**Comment by simprecicchiani** [comment]
Could you make a list of what works and what don't?

- [ ] Handoff
- [ ] Universal Clipboard
- [ ] iPhone Cellular Calls
- [ ] Text Message Forwarding
- [ ] Instant Hotspot
- [ ] Auto Unlock
- [ ] Continuity Camera
- [ ] Continuity Sketch
- [ ] Continuity Markup
- [ ] Sidecar
- [ ] AirDrop
- [ ] Apple Pay

 As of https://support.apple.com/en-us/HT204681

**Comment by alexdelli** [comment]
- [ ] Handoff
- [ ]   Universal Clipboard
- [ ]   iPhone Cellular Calls
- [ ]   Text Message Forwarding
- [ ]   Instant Hotspot
- [ ]   Auto Unlock
- [ ]   Continuity Camera
- [ ]   Continuity Sketch
- [ ]   Continuity Markup
- [ ]   Sidecar
- [ ]   AirDrop
- [ ]   Apple Pay

> Could you make a list of what works and what don't?
> 
> * [ ]  Handoff
> * [ ]  Universal Clipboard
> * [ ]  iPhone Cellular Calls
> * [ ]  Text Message Forwarding
> * [ ]  Instant Hotspot
> * [ ]  Auto Unlock
> * [ ]  Continuity Camera
> * [ ]  Continuity Sketch
> * [ ]  Continuity Markup
> * [ ]  Sidecar
> * [ ]  AirDrop
> * [ ]  Apple Pay
> 
> As of https://support.apple.com/en-us/HT204681

**Comment by simprecicchiani** [comment]
Waiting for new updates from you guys with Intel WLAN
