### ISSUE TITLE
TouchPad freezing

### ISSUE THREAD

**Issue by hirwa145** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#36]
Sometimes when i my laptop goes to sleep, when i wake it up after a while, the touchpad is not responding, it does not happen all the times but it does happen, the solution is use is restart the laptop, is there a way to solve this issue?

**Comment by mhl221135** [comment]
Also sometimes have this issue

**Comment by simprecicchiani** [comment]
I recently had some kernel panic with standby. Try to disable standby with `sudo pmset -a standby 0`.

**Comment by simprecicchiani** [comment]
Did it solved the issue?

**Comment by hirwa145** [comment]
Yes, the issue was solved. Thank you.
