### ISSUE TITLE
Upgrade to PCIe-NVMe SSD

### ISSUE THREAD

**Issue by hirwa145** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#40]
Did you use SSD or PCIe NVME, i want to upgrade to PCie NVME that works with Catalina/BigSur. Can you please specify which Storage you used?

**Comment by simprecicchiani** [comment]
My T460s is equipped with a SATA SSD but you'll be fine upgrading to NVMe. Just don't use the few models that are known to be faulty with macOS (like Samsung PM981).

**Comment by hirwa145** [comment]
Which model do you suggest i can use? For 512Gb Storage

**Comment by hirwa145** [comment]
After looking on internet, i found that SAMSUNG 970 EVO 500G NVME PCIe M.2-2280 SSD is compatible with the laptop, but want to make sure if it wont cause any problems with hackintosh

**Comment by hexart** [comment]
I‘m using westen data nvme ssd, its perfect, but a little bit high power consumption. 
<img width="325" alt="nvme" src="https://user-images.githubusercontent.com/5528016/97549056-e510a300-1a0a-11eb-9f28-f42868cb5bb1.png">

**Comment by simprecicchiani** [comment]
> After looking on internet, i found that SAMSUNG 970 EVO 500G NVME PCIe M.2-2280 SSD is compatible with the laptop, but want to make sure if it wont cause any problems with hackintosh

As mentioned in the [anti-mackintosh buyers guide](https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/Storage.html), unless the proper firmware is installed, a 970 EVO won't run on macOS.
