### ISSUE TITLE
The battery displays the wrong parameters.

### ISSUE THREAD

**Issue by xuandung38** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#43]
The battery displays the wrong parameters. Not with the remaining capacity. therefore there will be a situation where there is no low battery notification resulting in a sudden shutdown.

**Comment by xuandung38** [comment]
My origin DSDT + SSDT Here. 
Bios was mod

[origin.zip](https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore/files/5475497/origin.zip)

**Comment by simprecicchiani** [comment]
Which release are you on?

**Comment by xuandung38** [comment]
latest version bro!

**Comment by simprecicchiani** [comment]
Try [this](https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore/releases/tag/0.6.2.2) pre-release.

**Comment by xuandung38** [comment]
Still this error! :(

**Comment by mhl221135** [comment]
Hi, the last pre-release still has battery problems
the laptop is working fine and HWmonitorSMC shows the real capacity of my battery (I have very tired batteries, but there are about 2500mAh) during the discharge, the capacity continues to fall and near about 40% of the charge knocks out the message that the laptop will soon fall asleep and at this point the percentage stop changing, and the HWmonitorSMC shows 2500mAh and after a while the laptop just turns off )=

it seems that at the moment of notification of a low capacity, the laptop ceases to see the real battery capacity

**Comment by xuandung38** [comment]
Sloved
