### ISSUE TITLE
Reboots When in High Memory

### ISSUE THREAD

**Issue by KenWuqianghao** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#44]
First-time Hackintosh user and I followed the guide successfully till the end. But when I use Hackintosh do some tasks that are a little bit heavier, the hackintosh reboots.

**Comment by simprecicchiani** [comment]
Please try the [latest release](https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore/releases/tag/0.6.3).

**Comment by KenWuqianghao** [comment]
I installed my hackintosh yesterday, so I'm one hundred percent certain it is the newest version.

**Comment by simprecicchiani** [comment]
I released an updated version few hours ago. Anyway, it would be useful to see some logs when the reboot occurs.

**Comment by KenWuqianghao** [comment]
So generally I faced three situations that forced reboots, one is the attached image, saying memory status killing idle process. The second one says something about applekeymanagement. I wasn't able to get a image of the second one and the third simply doesn't display anything and reboots. 
![Uploading IMG_1778.JPG…]()

**Comment by simprecicchiani** [comment]
Don’t you have some system logs when the system reboots? Which are your specs?

**Comment by KenWuqianghao** [comment]
My specs are 512gb ssd, 4gb ram, intel GPU, and intel core i7. For the system logs, I'm not sure which part I should get, give me a moment to read through them.

**Comment by mhl221135** [comment]
Hello again))
I have some issues when running photoshop or other resource addicted programs my laptop sometimes go to log out and reopen programs whe i login in

i have aportunity to make this discusting photography but my knowlage in mac os is still miserible, so maybe you find the way to fix this issue

here is my system log which i copy from hackintool 
[err.txt](https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore/files/5502435/err.txt)



and here is discusting screenshot with info apearing when system loggin out)
![err1](https://user-images.githubusercontent.com/55281358/98392770-0d2e8080-2061-11eb-9580-7b79e9a7d668.jpg)

**Comment by KenWuqianghao** [comment]
> Hello again))
> I have some issues when running photoshop or other resource addicted programs my laptop sometimes go to log out and reopen programs whe i login in
> 
> i have aportunity to make this discusting photography but my knowlage in mac os is still miserible, so maybe you find the way to fix this issue
> 
> here is my system log which i copy from hackintool
> [err.txt](https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore/files/5502435/err.txt)
> 
> and here is discusting screenshot with info apearing when system loggin out)
> ![err1](https://user-images.githubusercontent.com/55281358/98392770-0d2e8080-2061-11eb-9580-7b79e9a7d668.jpg)

Same, I faced this issue severely too, especially I only have 4gb of Ram.

**Comment by meshack007** [comment]
I had the same issue #32 but after i added RAM it has helped. although it might not be a solution your looking for.

**Comment by mhl221135** [comment]
> I had the same issue #32 but after i added RAM it has helped. although it might not be a solution your looking for.

I alredy have 12gb of memory (also now i am on big sur and dont see this issue this time)

**Comment by meshack007** [comment]
@KenWuqianghao can you check your console and see if on crash reports you have WindowServer crashing? Maybe ram is not the problem

**Comment by KenWuqianghao** [comment]
> @KenWuqianghao can you check your console and see if on crash reports you have WindowServer crashing? Maybe ram is not the problem

I added 16gb of ram and the issue is solved.
