### ISSUE TITLE
Can't Enable Apple Service

### ISSUE THREAD

**Issue by KenWuqianghao** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#46]
The line of code doesn't work: git clone https://github.com/corpnewt/GenSMBIOS && cd GenSMBIOS && ./GenSMBIOS.command 

The error message says "Can't install the software because it is not currently available from the Software Update Server."

**Comment by SpacialLoser** [comment]
you can also get it from here: https://github.com/corpnewt/GenSMBIOS 😄

**Comment by simprecicchiani** [comment]
Semantics seems correct to me, it might have been a GitHub's server problem. Anyway, you can download the tool directly as @SpacialLoser said.
