### ISSUE TITLE
Sleep/Wake?

### ISSUE THREAD

**Issue by SpacialLoser** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#47]
Did anyone get this to work properly and not have a black screen w/ cursor?

**Comment by mhl221135** [comment]
I have all of things working, only have some bugs with battery percentage

**Comment by simprecicchiani** [comment]
Specs? Can you explain when it occurs?

**Comment by SpacialLoser** [comment]
I've fixed it, all it took was disabling external gpu with -wegnoegpu.

I'm on the T560 with i7 6600U
