### ISSUE TITLE
Automatic restart after shutdown problem

### ISSUE THREAD

**Issue by hexart** [simprecicchiani/Thinkpad-T460s-macOS-OpenCore#5]
Compile SSDT-EXT1-FixShutdown.dsl into aml file from OC-little and inject into config.plist(ACPI-Add) file will fix this problem.

**Comment by simprecicchiani** [comment]
Yes that's the fix if you don't make a custom USB ports kext or SSDT

**Comment by hexart** [comment]
> Yes that's the fix if you don't make a custom USB ports kext or SSDT

Actually I've created usb posts kext and loaded.

**Comment by simprecicchiani** [comment]
If USB setup is done properly you shouldn't need the patch.
