### ISSUE TITLE
AirportItlwm on BigSur

### ISSUE THREAD

**Issue by mhl221135** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#53]
Hello, this is not an issue but i just want to inform that AirportItlwm

not working corectly with Securebootmodel=Disabled at BigSur
But itlwm + Heliport working fine (exept slow speed on both methods)

**Comment by SpacialLoser** [comment]
Yeah i had slow speeds on 2.4ghz try switching to 5ghz for better speeds?

**Comment by mhl221135** [comment]
> Yeah i had slow speeds on 2.4ghz try switching to 5ghz for better speeds?

No i checked speed not change when i use 5ghz




Also latest appleitlwm alpha 1.2 working fine (still slow) but works

**Comment by simprecicchiani** [comment]
Big Sur can boot with SecureBoot = Default since OC 0.6.3.
There are two version of AirportItlwm included in the release, make sure you are using the big-sur one.

**Comment by mhl221135** [comment]
I use Latest alpha AirportItlwm with securebootmodel=disabled and it is working fine

**Comment by simprecicchiani** [comment]
It's recommended to set `SecureBoot` at least to `Default` as of OpenCore documentation to run Big Sur.
