### ISSUE TITLE
Does the new EFI support Big Sur?

### ISSUE THREAD

**Issue by KenWuqianghao** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#56]
Does the new EFI support update to Big Sur?

**Comment by hirwa145** [comment]
Yes, it supports Big Sur, updated from Big Sur Beta to Public Release 2 days ago. So smooth so far, no issue.

**Comment by KenWuqianghao** [comment]
So I can just update from the app store or system preference?

**Comment by hirwa145** [comment]
Yes you can. And update from there.
