### ISSUE TITLE
Which ssd 512 do you recomend for this laptop ?

### ISSUE THREAD

**Issue by mhl221135** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#57]

**Comment by simprecicchiani** [comment]
I recently installed a WD black sn750 and it works just fine. Any other ssd will work just fine but remember to avoid Samsung’s PM981 and PM961.

**Comment by mhl221135** [comment]
> I recently installed a WD black sn750 and it works just fine. Any other ssd will work just fine but remember to avoid Samsung’s PM981 and PM961.

Thanks, today buy sn750 and its working fine )

**Comment by hirwa145** [comment]
Is there noticeable improvement from using previous M.2 Sata SSD you had before?

**Comment by mhl221135** [comment]
> Is there noticeable improvement from using previous M.2 Sata SSD you had before?

I timed the start time of big sur and it changed by ~ 20 seconds on sata ssd it was 1:25 and on nvme 0:58

**Comment by simprecicchiani** [comment]
> Is there noticeable improvement from using previous M.2 Sata SSD you had before?

No, in daily task not at all. I upgraded only because I had an NVMe lying around after selling my desktop.
