### ISSUE TITLE
Trackpad kext doesn't work after sleep

### ISSUE THREAD

**Issue by zxcvb5788** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#64]
hello，bro，first thanks for your EFI，My laptop is Thinkpad x1c 2016, the computer configuration (I7 6600U, 16G, 2K, intel HD520) is similar to your T460S, your EFI file is almost perfect on my computer（catalina 10.15.7）, but there is a problem, Trackpad, Trackpoint and physical buttons after wake up from sleep There will be no response (the keyboard and mouse work normally). Do you have this problem?

**Comment by zxcvb5788** [comment]
I booted the system with a USB flash drive. Do you think this problem is caused by the automatic uninstallation of the USB flash drive during sleep? Because in addition to wake-up from sleep, Trackpad, Trackpoint and physical buttons work normally

**Comment by simprecicchiani** [comment]
There should be a bug in the trackpad driver. 
try to set `sudo pmset -a standby 0` in terminal.

**Comment by seanliu96** [comment]
I still have the same problem with my T460s. I tried the command above but it did not work.

**Comment by zxcvb5788** [comment]
> I still have the same problem with my T460s. I tried the command above but it did not work.

I solved it by using “VoodooPS2Controller.kext” 

<img width="938" alt="image" src="https://user-images.githubusercontent.com/59435992/113269832-701ffd00-930b-11eb-9306-c963ac205e99.png">

**Comment by seanliu96** [comment]
> > I still have the same problem with my T460s. I tried the command above but it did not work.
> 
> I solved it by using “VoodooPS2Controller.kext”
> 
> <img alt="image" width="938" src="https://user-images.githubusercontent.com/59435992/113269832-701ffd00-930b-11eb-9306-c963ac205e99.png">

Hi, thanks for your reply. I also used this kext, but the trackpad still occasionally failed to work after sleep. Haven't you encountered this problem?

**Comment by zxcvb5788** [comment]
> > > I still have the same problem with my T460s. I tried the command above but it did not work.
> > 
> > 
> > I solved it by using “VoodooPS2Controller.kext”
> > <img alt="image" width="938" src="https://user-images.githubusercontent.com/59435992/113269832-701ffd00-930b-11eb-9306-c963ac205e99.png">
> 
> Hi, thanks for your reply. I also used this kext, but the trackpad still occasionally failed to work after sleep. Haven't you encountered this problem?

I don't have this problem again after i use “VoodooPS2Controller.kext”, even sleep 2 days.  Is keyboard working correctly when the trackpad didn't work? Maybe you can provide an email and I'll send my VoodooPS2Controller.kext to you

**Comment by zxcvb5788** [comment]
> > > I still have the same problem with my T460s. I tried the command above but it did not work.
> > 
> > 
> > I solved it by using “VoodooPS2Controller.kext”
> > <img alt="image" width="938" src="https://user-images.githubusercontent.com/59435992/113269832-701ffd00-930b-11eb-9306-c963ac205e99.png">
> 
> Hi, thanks for your reply. I also used this kext, but the trackpad still occasionally failed to work after sleep. Haven't you encountered this problem?

讲中文？

**Comment by seanliu96** [comment]
> > > > I still have the same problem with my T460s. I tried the command above but it did not work.
> > > 
> > > 
> > > I solved it by using “VoodooPS2Controller.kext”
> > > <img alt="image" width="938" src="https://user-images.githubusercontent.com/59435992/113269832-701ffd00-930b-11eb-9306-c963ac205e99.png">
> > 
> > 
> > Hi, thanks for your reply. I also used this kext, but the trackpad still occasionally failed to work after sleep. Haven't you encountered this problem?
> 
> I don't have this problem again after i use “VoodooPS2Controller.kext”, even sleep 2 days. Is keyboard working correctly when the trackpad didn't work? Maybe you can provide an email and I'll send my VoodooPS2Controller.kext to you

You are so kind. My email is seanliu96@outlook.com . Thanks.

**Comment by seanliu96** [comment]
> > > > I still have the same problem with my T460s. I tried the command above but it did not work.
> > > 
> > > 
> > > I solved it by using “VoodooPS2Controller.kext”
> > > <img alt="image" width="938" src="https://user-images.githubusercontent.com/59435992/113269832-701ffd00-930b-11eb-9306-c963ac205e99.png">
> > 
> > 
> > Hi, thanks for your reply. I also used this kext, but the trackpad still occasionally failed to work after sleep. Haven't you encountered this problem?
> 
> 讲中文？

可以。但是你的办法可能可以帮助到其他国家的一些朋友。

Okay. But maybe guys from other countries can benefit from your solution.

**Comment by seanliu96** [comment]
Seems solved. Thank @zxcvb5788 for providing his kext. Currently, the 2.1.7 version of VoodooPS2Controller.kext works well. If someone has the same problem, please try https://github.com/acidanthera/VoodooPS2/releases/download/2.1.7/VoodooPS2Controller-2.1.7-RELEASE.zip

**Comment by mhl221135** [comment]
> Seems solved. Thank @zxcvb5788 for providing his kext. Currently, the 2.1.7 version of VoodooPS2Controller.kext works well. If someone has the same problem, please try https://github.com/acidanthera/VoodooPS2/releases/download/2.1.7/VoodooPS2Controller-2.1.7-RELEASE.zip

you using hiberinate mode ?

**Comment by seanliu96** [comment]
> > Seems solved. Thank @zxcvb5788 for providing his kext. Currently, the 2.1.7 version of VoodooPS2Controller.kext works well. If someone has the same problem, please try https://github.com/acidanthera/VoodooPS2/releases/download/2.1.7/VoodooPS2Controller-2.1.7-RELEASE.zip
> 
> you using hiberinate mode ?


I am not sure whether mac os the support hiberinate mode.Previously, I encountered the bug when my laptop automatically slept.

**Comment by mhl221135** [comment]
Resolved in latest EFI update sleep-wake working fine
