### ISSUE TITLE
Thinkpad X260 with 2 Batteries

### ISSUE THREAD

**Issue by taktiker12** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#67]
ciao siempri
thank you for your great contribution to help us using your work ; well , I am on Thinkpad x260 i5 6300U with internal and external battery . I am confused about the battery status that is showing only one battery . so I have a question , shall I modify something to get 2 batteries showing on the status bar ?
thank You

**Comment by simprecicchiani** [comment]
Try to install HWmonitor and see what it shows.

**Comment by taktiker12** [comment]
thank you for reply and advice .I will install hwmonitor

**Comment by taktiker12** [comment]
ok, it shows under batteries only internal battery

**Comment by taktiker12** [comment]
![Screenshot 2020-12-03 at 18 56 18](https://user-images.githubusercontent.com/9823492/101068633-40e5c300-3599-11eb-91a4-275008a0ffd3.png)

**Comment by mhl221135** [comment]
You cant get 2 batteries showed in your bar (this efi uses patch that combines 2 batteries as one logical)
