### ISSUE TITLE
cmos checksum bad after long sleep

### ISSUE THREAD

**Issue by mhl221135** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#68]
After long sleep on last efi and last release Big Sur i get "cmos checksum bad"
Then when i press "press esc to continue boot" i see opencore picket and when i choose my os is is showing me black screen without any verbouse

Then i hold pwr button and restart laptop and on this start up cycle everything working fine

What can it be?

**Comment by mhl221135** [comment]
![VID_2020-12-11-10-29-13-009_exported_0_1607678170059.jpg](https://user-images.githubusercontent.com/55281358/101885070-48f9c000-3ba2-11eb-912c-3fd70ec41a2d.jpg)

**Comment by NotNocky** [comment]
I got something similar but it was after the laptop had died in sleep

**Comment by simprecicchiani** [comment]
Did you had standby turned on or off?

**Comment by findyy99** [comment]
I am T450S, I have the same question, I have enable `DisableRtcChecksum`.Does't work.

**Comment by mhl221135** [comment]
Hello, and thank you for your work, i disable stand by and update my efi to 0.3.4 and i dont see this error anymore

> Did you had standby turned on or off?
