### ISSUE TITLE
Wifi broken on BigSur?

### ISSUE THREAD

**Issue by lozzareeves** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#69]
My wifi no longer works now that I've updated to bigsur?
The icon in the menu bar will say it's on, but when you check in System Preferences it's off. Clicking Turn WiFi on does nothing?

**Comment by lozzareeves** [comment]
Ah.. sorted by deleting the airport kext and renaming the bigsur one.
I donated to you as a thank you for this guide as well by the way! thanks.

**Comment by simprecicchiani** [comment]
Thank you!
