### ISSUE TITLE
Choppy scroll?

### ISSUE THREAD

**Issue by j-a-y-m** [simprecicchiani/Thinkpad-T460s-macOS-OpenCore#7]
Anybody else facing choppy scroll? Any known fix or it? 
GPU acceleration is enabled and all other animations are smooth except scrolling and other trackpad gestures.

**Comment by simprecicchiani** [comment]
Which Thinkpad model do you have?

**Comment by j-a-y-m** [comment]
oh my bad should have mentioned 
Its an X260 
Everything else Is working perfectly fine with your efi folder

**Comment by simprecicchiani** [comment]
There are a couple of X260's hackintosh config here on GitHub, look for their PS2K SSDT and you'll find a solution for that.
