### ISSUE TITLE
Intel Power Gadget doesn’t work with release 0.6.4

### ISSUE THREAD

**Issue by simprecicchiani** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#75]

**Comment by simprecicchiani** [comment]
Strangely it works after updating to macOS 11.1 (same IPG ver 3.7.0)

**Comment by cty12** [comment]
I can confirm that Intel Power Gadget works on `11.0.1` as well (for both `0.6.3` and `0.6.4`).
