### ISSUE TITLE
Unknown Startup Message

### ISSUE THREAD

**Issue by KenWuqianghao** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#77]
I received this message saying "OCS: Failed to calculate size of false field containing <empty> as type integer, context <PlayChime>!". The startup was perfectly fine and working. I'm just wondering if this is some potential issue I need to fix or recommended to solve. 
![IMG_1896](https://user-images.githubusercontent.com/20444505/102109371-40201d00-3e34-11eb-8a8a-e988394b9f17.JPG)

**Comment by cdpidan** [comment]
Change UEFI-> Audio-> PlayChime:Auto

**Comment by KenWuqianghao** [comment]
Solved, thank you very much

**Comment by simprecicchiani** [comment]
> Solved, thank you very much

Was it set differently in release's config.plist?

**Comment by KenWuqianghao** [comment]
> > Solved, thank you very much
> 
> Was it set differently in release's config.plist?

Yes it was

**Comment by simprecicchiani** [comment]
Ok thanks, I'll fix it in the next release.
