### ISSUE TITLE
Broken RAM slot causes OS's crash

### ISSUE THREAD

**Issue by KenWuqianghao** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#78]
My hardware is 512GB SSD, 4GB soldered plus 16GB RAM, i7 6th gen. The system won't continue working or startup if I don't use the solution below.

I've found a bizarre solution through this issue which is holding the extra RAM card tightly to the RAM slot and the system would start up and function normally, so I put a stack My hardware is 512GB SSD, 4GB soldered plus 16GB RAM, i7 6th gen. The system won't continue working or startup whenever there are small collisions or turbulence. Does anyone have a similar issue or has a proper solution for it?

**Comment by mhl221135** [comment]
it looks like the contact of the RAM disappears with jolts, you can try to clean its contacts with a pencil eraser and insert it correctly until it clicks

**Comment by KenWuqianghao** [comment]
I had some videos demonstrating my situation even after cleaning the slot. Here they are:
Without Extra RAM: 
[https://e.pcloud.link/publink/show?code=XZGd97Z6LHxuCBP5PRVKBvjxAsIO8pVYgUX(https://e.pcloud.link/publink/show?code=XZGd97Z6LHxuCBP5PRVKBvjxAsIO8pVYgUX)
With RAM:
[https://e.pcloud.link/publink/show?code=XZbq97ZMsKrR3BdCbLMBuzL77glIu8DEMsV](https://e.pcloud.link/publink/show?code=XZbq97ZMsKrR3BdCbLMBuzL77glIu8DEMsV)
With RAM and holding it against the motherboard: [https://e.pcloud.link/publink/showcode=XZRq97Zr2RkkkNjLkuVM0nupj1Sm4HrpQdk(https://e.pcloud.link/publink/showcode=XZRq97Zr2RkkkNjLkuVM0nupj1Sm4HrpQdk)

**Comment by simprecicchiani** [comment]
Have you tried booting another OS? You could try a live Linux distro.

**Comment by KenWuqianghao** [comment]
I'm not sure how that will help solve the issue, but I will be trying it now.

**Comment by KenWuqianghao** [comment]
Okay, I just extra tried booting from a live Linux distro. Results are the same. Without the RAM or with me pressing the RAM, the OS starts perfectly. If I'm not pressing against the RAM, the issue still occurs, the OS just crashes and display some green lines. At this point, I think it is my hardware issue.
![IMG_1916](https://user-images.githubusercontent.com/20444505/102686275-c21e9600-41e6-11eb-95bd-1524f6db1ddf.JPG)

**Comment by simprecicchiani** [comment]
Sorry to hear that, it's very unfortunate. You could give it a try with another ram stick but the slot is likely to be broken.
