### ISSUE TITLE
0.6.5 halting on voodooRMI.kext

### ISSUE THREAD

**Issue by mhl221135** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#83]
Latest commit efi issue

Halting on VoodooRMI.kext  i just replace it by kext from previous commit and its now working![MVIMG_20210106_001916.jpg](https://user-images.githubusercontent.com/55281358/103706392-62313900-4fb5-11eb-8eed-3502ca0f5a90.jpg)

**Comment by simprecicchiani** [comment]
VoodooTrackpoint.kext plugin is not included in VoodooRMI 1.3 and the entry in config.plist wasn't changed accordingly. It looks like this version has some other issues so I'll roll back to the previous.
