### ISSUE TITLE
0.6.5 Brightness hot keys not working

### ISSUE THREAD

**Issue by mhl221135** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#84]
0.6.5 Brightness hot keys not working
Brightness working only from this Big sur pane 
Sound conteol working fine
I am using latest YogaSmc app
![Снимок экрана 2021-01-05 в 18 08 26](https://user-images.githubusercontent.com/55281358/103669463-09e04400-4f81-11eb-8aa1-9bc1b3357ad7.png)

**Comment by simprecicchiani** [comment]
I forgot to add BrightnessKeys.kext, I'm going to include it in the next commit.
