### ISSUE TITLE
How to set heberinatemode 25 work?

### ISSUE THREAD

**Issue by mhl221135** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#90]
my battery discharging in hiberinatemode 25 standby1 in config hiberinatemode = auto how can i check hiberinating laptop or no ?

**Comment by alexdelli** [comment]
Mine discharging about 13% in 24h in Hibernate mode. I think it is a wonderful result

**Comment by mhl221135** [comment]
I tried to change my hiberinate mode to 25 and i just have cmos error and after few reboots my system tell that it is shutted down with error (looks like reset nor hiberinate(= )

**Comment by mhl221135** [comment]
Resolution in other issue
