### ISSUE TITLE
OpenCorePkg  release 0.6.7

### ISSUE THREAD

**Issue by iTer99** [simprecicchiani/ThinkPad-T460s-macOS-OpenCore#99]
update 0.6.7 please and thank you so much for continue this project

**Comment by simprecicchiani** [comment]
[There you go](https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore/releases/tag/0.6.7).
Haven't tested it though.

**Comment by iTer99** [comment]
> [Của bạn đây](https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore/releases/tag/0.6.7) .
> Chưa thử nghiệm nó mặc dù.
> 
> Chỉnh sửa: Đã kiểm tra, đang hoạt động.

thank you so much, this working very good

**Comment by MarkMorrow** [comment]
The serial number that shows in the About screen is now different.  I transferred over the entries in /EFI/OC/Config.plist within PlatformInfo -> Generic and double checked it is correct.  Messaging, iCloud and Apple watch unlock still working, so not sure if this is a feature or and issue.  Thoughts?

**Comment by simprecicchiani** [comment]
I didn't noticed that. Mine is showing a different SN too. I'll take a look at OpenCore's changelog closely.

**Comment by MarkMorrow** [comment]
Thanks much. Glad it is not just me.  I just opened a new issue (since this one is closed).  Came back to remove my post here, but will leave it since you have already replied.

**Comment by MarkMorrow** [comment]
Fixed in v0.6.8 in @duszmox 's fork:
[https://github.com/duszmox/Thinkpad-T460s-macOS-OpenCore](https://github.com/duszmox/Thinkpad-T460s-macOS-OpenCore)
